stages:
- build
- combine

build amd64:
  tags:
  - macos
  - amd64
  stage: build
  variables:
    MACOSX_DEPLOYMENT_TARGET: "10.13"
  before_script:
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  script:
  - mkdir mautrix-imessage-nosip-amd64
  - go build -ldflags "$GO_LDFLAGS" -o mautrix-imessage-nosip-amd64/mautrix-imessage-nosip
  - install_name_tool -change /usr/local/opt/libolm/lib/libolm.3.dylib @rpath/libolm.3.dylib mautrix-imessage-nosip-amd64/mautrix-imessage-nosip
#  - install_name_tool -change /usr/local/opt/libheif/lib/libheif.1.dylib @rpath/libheif.1.dylib mautrix-imessage-nosip-amd64/mautrix-imessage-nosip
  - install_name_tool -add_rpath @executable_path mautrix-imessage-nosip-amd64/mautrix-imessage-nosip
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib mautrix-imessage-nosip-amd64/mautrix-imessage-nosip
  - cp /usr/local/opt/libolm/lib/libolm.3.dylib mautrix-imessage-nosip-amd64/
#  - cp /usr/local/opt/libheif/lib/libheif.1.dylib mautrix-imessage-nosip-amd64/
  - cp example-config.yaml mautrix-imessage-nosip-amd64/
  artifacts:
    paths:
    - mautrix-imessage-nosip-amd64
    expire_in: 1 day

build arm64:
  tags:
  - macos
  - arm64
  stage: build
  variables:
    MACOSX_DEPLOYMENT_TARGET: "10.13"
  before_script:
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  - export LIBRARY_PATH=/opt/homebrew/lib
  - export CPATH=/opt/homebrew/include
  - export PATH=/opt/homebrew/bin:$PATH
  script:
  - mkdir mautrix-imessage-nosip-arm64
  - go build -ldflags "$GO_LDFLAGS" -o mautrix-imessage-nosip-arm64/mautrix-imessage-nosip
  - install_name_tool -change /opt/homebrew/opt/libolm/lib/libolm.3.dylib @rpath/libolm.3.dylib mautrix-imessage-nosip-arm64/mautrix-imessage-nosip
#  - install_name_tool -change /opt/homebrew/opt/libheif/lib/libheif.1.dylib @rpath/libheif.1.dylib mautrix-imessage-nosip-arm64/mautrix-imessage-nosip
  - install_name_tool -add_rpath @executable_path mautrix-imessage-nosip-arm64/mautrix-imessage-nosip
  - install_name_tool -add_rpath /opt/homebrew/opt/libolm/lib mautrix-imessage-nosip-arm64/mautrix-imessage-nosip
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib mautrix-imessage-nosip-arm64/mautrix-imessage-nosip
  - cp /opt/homebrew/opt/libolm/lib/libolm.3.dylib mautrix-imessage-nosip-arm64/
#  - cp /opt/homebrew/opt/libheif/lib/libheif.1.dylib mautrix-imessage-nosip-arm64/
  - cp example-config.yaml mautrix-imessage-nosip-arm64/
  artifacts:
    paths:
    - mautrix-imessage-nosip-arm64
    expire_in: 1 day

build ios arm64:
  tags:
  - macos
  - arm64
  stage: build
  variables:
    CGO_ENABLED: 1
    GOARCH: arm64
    GOOS: ios
    IPHONEOS_DEPLOYMENT_TARGET: "7.0"
    SDK: iphoneos
    ARCH: arm64
  before_script:
  - export SDK_PATH=$(xcrun -sdk $SDK -show-sdk-path)
  - export CLANG=$(xcrun -sdk $SDK -find clang)
  - export LIBRARY_PATH=$HOME/lib/arm64
  - export CPATH=/opt/homebrew/include
  - export PATH=/opt/homebrew/bin:$PATH
  - export CC=$(pwd)/clangwrap.sh
  - export CXX=$CC
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  script:
  - mkdir mautrix-imessage-nosip-ios-arm64
  - go build -tags ios -ldflags "$GO_LDFLAGS" -o mautrix-imessage-nosip-ios-arm64/mautrix-imessage-nosip
  - install_name_tool -change build/libolm.dylib.3.2.4 @executable_path/libolm.3.dylib mautrix-imessage-nosip-ios-arm64/mautrix-imessage-nosip
  - ldid -S mautrix-imessage-nosip-ios-arm64/mautrix-imessage-nosip
  - cp $HOME/lib/arm64/libolm.dylib mautrix-imessage-nosip-ios-arm64/libolm.3.dylib
  - ldid -S mautrix-imessage-nosip-ios-arm64/libolm.3.dylib
  artifacts:
    paths:
    - mautrix-imessage-nosip-ios-arm64
    expire_in: 1 day

build universal:
  stage: combine
  tags:
  - macos
  - arm64
  variables:
    GIT_STRATEGY: none
  dependencies:
  - build amd64
  - build arm64
  needs:
  - build amd64
  - build arm64
  script:
  - lipo -create -output libolm.3.dylib mautrix-imessage-nosip-arm64/libolm.3.dylib mautrix-imessage-nosip-amd64/libolm.3.dylib
#  - lipo -create -output libheif.1.dylib mautrix-imessage-nosip-arm64/libheif.1.dylib mautrix-imessage-nosip-amd64/libheif.1.dylib
  - lipo -create -output mautrix-imessage-nosip mautrix-imessage-nosip-arm64/mautrix-imessage-nosip mautrix-imessage-nosip-amd64/mautrix-imessage-nosip
  - cp mautrix-imessage-nosip-arm64/example-config.yaml .
  artifacts:
    name: mautrix-imessage-nosip-universal
    paths:
    - libolm.3.dylib
#    - libheif.1.dylib
    - mautrix-imessage-nosip
    - example-config.yaml
    expire_in: 30 days
